include($$PWD/concurrency/concurrency.pri)
include($$PWD/netapi/netapi.pri)
include($$PWD/audioapi/audioapi.pri)
include($$PWD/videoapi/videoapi.pri)
include($$PWD/utils/utils.pri)
include($$PWD/opengl/opengl.pri)
